language: ruby
cache: bundler
rvm:
  - 2.5
  - 2.6
  - jruby
  - truffleruby
matrix:
  fast_finish: true
  allow_failures:
    - rvm: jruby
    - rvm: truffleruby
script:
  - bundle exec rake rubocop
  - bundle exec rake spec
